
import type { AspectRatio, VisualStyle, NarrationStyleKey } from './types';

export const NARRATION_STYLES: { id: NarrationStyleKey; aiPromptValue: string; translationKey: string; }[] = [
    { id: 'DOCUMENTARY', aiPromptValue: 'Documentary', translationKey: 'documentary' },
    { id: 'NARRATOR', aiPromptValue: 'Biblical Narrator', translationKey: 'narrator' },
    { id: 'PREACHER', aiPromptValue: 'Preacher', translationKey: 'preacher' },
    { id: 'DEBATE', aiPromptValue: 'Scientific Debate', translationKey: 'debate' },
    { id: 'STORY', aiPromptValue: 'Biblical Storyteller', translationKey: 'story' },
    { id: 'MICRO', aiPromptValue: 'Micro-Story', translationKey: 'microStory' },
    { id: 'FIRST_PERSON', aiPromptValue: 'First Person Podcast', translationKey: 'firstPerson' },
    { id: 'YOUTUBE_SCRIPT', aiPromptValue: 'YouTube Script', translationKey: 'youtubeScript' },
];

export const ASPECT_RATIOS: AspectRatio[] = ['1:1', '16:9', '9:16', '4:3', '3:4'];

export const VISUAL_STYLES: { id: VisualStyle; translationKey: string; }[] = [
    { id: 'Cinematic', translationKey: 'styleCinematic' },
    { id: 'Más Realista', translationKey: 'styleMasRealista' },
    { id: 'Realistic', translationKey: 'styleRealistic' },
    { id: 'Documentary Photo', translationKey: 'styleDocumentaryPhoto' },
    { id: 'Painted', translationKey: 'stylePainted' },
    { id: 'For Kids (Cartoon)', translationKey: 'styleForKidsCartoon' },
    { id: 'Comic Book', translationKey: 'styleComicBook' },
];

export const CONTENT_CATEGORIES: { id: string; translationKey: string; }[] = [
    { id: 'All', translationKey: 'categoryAll' },
    { id: 'Life of Jesus (In-Depth)', translationKey: 'categoryLifeOfJesusInDepth' },
    { id: 'Motivational (Jesus\'s Words)', translationKey: 'categoryMotivational' },
    { id: 'Miracles', translationKey: 'categoryMiracles' },
    { id: 'Parables', translationKey: 'categoryParables' },
    { id: 'History of Israel', translationKey: 'categoryHistoryOfIsrael' },
    { id: 'Prophecy', translationKey: 'categoryProphecy' },
    { id: 'Apocalypse', translationKey: 'categoryApocalypse' },
    { id: 'Angels', translationKey: 'categoryAngels' },
    { id: 'Women in the Bible', translationKey: 'categoryWomenInTheBible' },
    { id: 'Controversial Topics', translationKey: 'categoryControversial' },
];

export const JESUS_LIFE_TOPICS = [
    { id: 'miracles', translationKey: 'jesusTopicMiracles', icon: '✨' },
    { id: 'parables', translationKey: 'jesusTopicParables', icon: '📖' },
    { id: 'relationships', translationKey: 'jesusTopicRelationships', icon: '👥' },
    { id: 'teachings', translationKey: 'jesusTopicTeachings', icon: '🗣️' },
    { id: 'passion', translationKey: 'jesusTopicPassion', icon: '✝️' },
    { id: 'early_life', translationKey: 'jesusTopicEarlyLife', icon: '👶' },
];


export const PROMPT_COLORS = [
    'border-sky-500',
    'border-emerald-500',
    'border-amber-500',
    'border-rose-500',
    'border-indigo-500',
    'border-fuchsia-500',
    'border-teal-500',
    'border-orange-500',
];

export const KEY_BIBLICAL_FIGURES = [
    // Genesis
    { id: 'adam', translationKey: 'figureAdam' },
    { id: 'eve', translationKey: 'figureEve' },
    { id: 'cain', translationKey: 'figureCain' },
    { id: 'abel', translationKey: 'figureAbel' },
    { id: 'enoch', translationKey: 'figureEnoch' },
    { id: 'noah', translationKey: 'figureNoah' },
    { id: 'abraham', translationKey: 'figureAbraham' },
    { id: 'sarah', translationKey: 'figureSarah' },
    { id: 'lot', translationKey: 'figureLot' },
    { id: 'isaac', translationKey: 'figureIsaac' },
    { id: 'rebekah', translationKey: 'figureRebekah' },
    { id: 'jacob', translationKey: 'figureJacob' },
    { id: 'esau', translationKey: 'figureEsau' },
    { id: 'rachel', translationKey: 'figureRachel' },
    { id: 'leah', translationKey: 'figureLeah' },
    { id: 'joseph_son_of_jacob', translationKey: 'figureJosephSonOfJacob' },
    // Exodus - Deuteronomy
    { id: 'moses', translationKey: 'figureMoses' },
    { id: 'aaron', translationKey: 'figureAaron' },
    { id: 'miriam', translationKey: 'figureMiriam' },
    { id: 'pharaoh_of_exodus', translationKey: 'figurePharaohOfExodus' },
    { id: 'joshua', translationKey: 'figureJoshua' },
    { id: 'caleb', translationKey: 'figureCaleb' },
    { id: 'balaam', translationKey: 'figureBalaam' },
    // Judges
    { id: 'deborah', translationKey: 'figureDeborah' },
    { id: 'gideon', translationKey: 'figureGideon' },
    { id: 'samson', translationKey: 'figureSamson' },
    { id: 'delilah', translationKey: 'figureDelilah' },
    { id: 'ruth', translationKey: 'figureRuth' },
    { id: 'boaz', translationKey: 'figureBoaz' },
    { id: 'samuel', translationKey: 'figureSamuel' },
    // Kings
    { id: 'king_saul', translationKey: 'figureKingSaul' },
    { id: 'david', translationKey: 'figureDavid' },
    { id: 'goliath', translationKey: 'figureGoliath' },
    { id: 'jonathan', translationKey: 'figureJonathan' },
    { id: 'bathsheba', translationKey: 'figureBathsheba' },
    { id: 'solomon', translationKey: 'figureSolomon' },
    { id: 'queen_of_sheba', translationKey: 'figureQueenOfSheba' },
    { id: 'rehoboam', translationKey: 'figureRehoboam' },
    { id: 'jeroboam', translationKey: 'figureJeroboam' },
    { id: 'elijah', translationKey: 'figureElijah' },
    { id: 'elisha', translationKey: 'figureElisha' },
    { id: 'ahab', translationKey: 'figureAhab' },
    { id: 'jezebel', translationKey: 'figureJezebel' },
    { id: 'hezekiah', translationKey: 'figureHezekiah' },
    { id: 'josiah', translationKey: 'figureJosiah' },
    // Prophets
    { id: 'isaiah', translationKey: 'figureIsaiah' },
    { id: 'jeremiah', translationKey: 'figureJeremiah' },
    { id: 'ezekiel', translationKey: 'figureEzekiel' },
    { id: 'daniel', translationKey: 'figureDaniel' },
    { id: 'shadrach', translationKey: 'figureShadrach' },
    { id: 'meshach', translationKey: 'figureMeshach' },
    { id: 'abednego', translationKey: 'figureAbednego' },
    { id: 'hosea', translationKey: 'figureHosea' },
    { id: 'joel', translationKey: 'figureJoel' },
    { id: 'amos', translationKey: 'figureAmos' },
    { id: 'jonah', translationKey: 'figureJonah' },
    { id: 'micah', translationKey: 'figureMicah' },
    // Post-Exile
    { id: 'ezra', translationKey: 'figureEzra' },
    { id: 'nehemiah', translationKey: 'figureNehemiah' },
    { id: 'esther', translationKey: 'figureEsther' },
    { id: 'mordecai', translationKey: 'figureMordecai' },
    { id: 'haman', translationKey: 'figureHaman' },
    { id: 'job', translationKey: 'figureJob' },
    // New Testament - Gospels
    { id: 'jesus_christ', translationKey: 'figureJesusChrist' },
    { id: 'mary_mother_of_jesus', translationKey: 'figureMaryMotherOfJesus' },
    { id: 'joseph_father_of_jesus', translationKey: 'figureJosephFatherOfJesus' },
    { id: 'john_the_baptist', translationKey: 'figureJohnTheBaptist' },
    { id: 'peter', translationKey: 'figurePeter' },
    { id: 'andrew', translationKey: 'figureAndrew' },
    { id: 'james_son_of_zebedee', translationKey: 'figureJamesSonOfZebedee' },
    { id: 'john_apostle', translationKey: 'figureJohnApostle' },
    { id: 'philip', translationKey: 'figurePhilip' },
    { id: 'bartholomew', translationKey: 'figureBartholomew' },
    { id: 'thomas', translationKey: 'figureThomas' },
    { id: 'matthew', translationKey: 'figureMatthew' },
    { id: 'james_son_of_alphaeus', translationKey: 'figureJamesSonOfAlphaeus' },
    { id: 'thaddeus', translationKey: 'figureThaddeus' },
    { id: 'simon_the_zealot', translationKey: 'figureSimonTheZealot' },
    { id: 'judas_iscariot', translationKey: 'figureJudasIscariot' },
    { id: 'mary_magdalene', translationKey: 'figureMaryMagdalene' },
    { id: 'martha', translationKey: 'figureMartha' },
    { id: 'mary_of_bethany', translationKey: 'figureMaryOfBethany' },
    { id: 'lazarus', translationKey: 'figureLazarus' },
    { id: 'nicodemus', translationKey: 'figureNicodemus' },
    { id: 'zacchaeus', translationKey: 'figureZacchaeus' },
    { id: 'pontius_pilate', translationKey: 'figurePontiusPilate' },
    { id: 'herod_the_great', translationKey: 'figureHerodTheGreat' },
    { id: 'herod_antipas', translationKey: 'figureHerodAntipas' },
    { id: 'caiaphas', translationKey: 'figureCaiaphas' },
    { id: 'joseph_of_arimathea', translationKey: 'figureJosephOfArimathea' },
    // Acts and Epistles
    { id: 'apostle_paul', translationKey: 'figureApostlePaul' },
    { id: 'luke', translationKey: 'figureLuke' },
    { id: 'mark', translationKey: 'figureMark' },
    { id: 'barnabas', translationKey: 'figureBarnabas' },
    { id: 'stephen', translationKey: 'figureStephen' },
    { id: 'cornelius', translationKey: 'figureCornelius' },
    { id: 'lydia', translationKey: 'figureLydia' },
    { id: 'priscilla', translationKey: 'figurePriscilla' },
    { id: 'aquila', translationKey: 'figureAquila' },
    { id: 'timothy', translationKey: 'figureTimothy' },
    { id: 'titus', translationKey: 'figureTitus' },
    { id: 'philemon', translationKey: 'figurePhilemon' },
    { id: 'james_brother_of_jesus', translationKey: 'figureJamesBrotherOfJesus' }
];